database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres123
  url: jdbc:postgresql://db:5432/blog
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect